version: 2
updates:
  - package-ecosystem: cargo
    schedule:
      interval: weekly
      time: "09:00"
    open-pull-requests-limit: 10
    target-branch: wasm

  - package-ecosystem: npm
    schedule:
      interval: weekly
      time: "09:00"
    open-pull-requests-limit: 10
    target-branch: wasm
