language: node_js
node_js:
- 10

addons:
  apt:
    packages:
    - texlive

cache:
  yarn: true
  directories:
  - ./node_modules

script:
- yarn build

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  skip_cleanup: true

notifications:
  email:
    on_failure: change
    on_success: change
