language: node_js
node_js:
  - "8"

cache:
  directories:
     - ./node_modules
     - ./functions/node_modules

script:
  - node scripts/check
  - yarn build

after_success:
  - yarn global add firebase-tools
  - test $TRAVIS_BRANCH = "dev" && firebase use dev
  - test $TRAVIS_BRANCH = "master" && firebase use default
  - firebase deploy --non-interactive --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
