language: node_js
node_js:
  - "7"

before_script:
  - yarn setup

matrix:
  include:
    - env: BUILD_DIR='amp'
    - env: BUILD_DIR='react'
script:
  - cd $BUILD_DIR
  - yarn
  - yarn setup
  - yarn build

after_success:
  - cd $TRAVIS_BUILD_DIR
  - yarn global add firebase-tools
  - test $TRAVIS_BRANCH = "dev" && firebase use dev
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
