language: node_js
node_js:
  - "7"

before_script:
  - yarn

script:
  - bash scripts/build.sh

after_success:
  - yarn global add firebase-tools
  - test $TRAVIS_BRANCH = "dev" && firebase use dev
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
