language: rust

rust:
  - nightly

cache:
  cargo: true
  yarn: true
  directories:
    - gen/target
    - web/node_modules

before_install:
  - nvm install 11
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - cargo run --manifest-path gen/Cargo.toml
  - yarn --cwd web/
  - yarn --cwd web/ build

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change
