language: node_js
node_js:
  - "8"

cache:
  directories:
     - ./node_modules
     - ./functions/node_modules

script:
  - yarn build

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  skip_cleanup: true

notifications:
  email:
    on_failure: change
    on_success: change
