language: node_js
node_js:
  - "6"

branches:
  only:
    - master

before_script:
  - git clone https://github.com/PoiScript/Solomon-Post.git src/markdown
  - mkdir src/json
  - npm install

script:
  - npm run render
  - npm run build

after_success:
  - npm install -g firebase-tools
  - firebase deploy --token $FIREBASE_TOKEN
  - npm install -g angular-cli-ghpages
  - angular-cli-ghpages --repo=https://$GITHUB_TOKEN@github.com/PoiScript/poiscript.github.io.git --branch=master --message="Update Solomon"

notifications:
  email:
    on_failure: change
    on_success: change
