[package]
name = "solomon"
version = "2.0.0"
authors = ["PoiScript <poiscript@gmail.com>"]
description = "PoiScript's Blog"
edition = "2018"
homepage = "https://blog.poi.cat"
license = "MIT"
publish = false
repository = "https://github.com/PoiScript/solomon"

[dependencies]
bincode = "1.3.3"
chrono = { version = "0.4.19", default-features = false, features = [
    "clock",
    "wasmbind",
    "serde"
] }
console_error_panic_hook = "0.1.6"
imagesize = "0.8.8"
js-sys = "0.3.48"
json = "0.12.4"
maud = "0.22.2"
orgize = { version = "0.8.4", default-features = false }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
wasm-bindgen = "0.2.71"
web-sys = { version = "0.3.48", features = ["console"] }
wee_alloc = "0.4.5"

[profile.release]
lto = true

[lib]
crate-type = ["cdylib", "rlib"]
