[package]
name = "solomon"
version = "0.1.0"
authors = ["PoiScript <poiscript@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
imagesize = "0.6"
orgize = { git = "https://github.com/PoiScript/orgize" }
