name: build

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Cache
        uses: actions/cache@v1
        with:
          path: web/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install node
        uses: actions/setup-node@master
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: Build
        run: yarn zx build.mjs
        env:
          KV_NAMESPACE_ID: e994fdd7add54bee9b3e905bbad1ce61
          ACCOUNT_ID: f1c2ab938f91fa76af879185e872f215
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
          WORKER_NAME: ${{ github.ref == 'refs/heads/master' && 'blog' || 'blogdev' }}
