name: publish

on:
  push:
    paths:
      - src/**
      - web/**
      - worker/**
      - .github/workflows/publish.yml
  pull_request:
    paths:
      - src/**
      - web/**
      - worker/**

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Cache
        uses: actions/cache@v1
        with:
          path: web/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install node
        uses: actions/setup-node@master
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: Build
        run: |
          yarn run wasm:worker
          yarn run build:worker
        env:
          NODE_ENV: production

      - name: Publish
        if: github.ref == 'refs/heads/wasm'
        run: node scripts/publish.js
        env:
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
