name: upload

on:
  push:
    paths:
      - assets/**
      - content/**
      - .github/workflows/upload.yml

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Cache
        uses: actions/cache@v1
        with:
          path: web/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install node
        uses: actions/setup-node@master
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: Upload
        run: node scripts/upload.js
        env:
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
